manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: thxtech
      url-base: https://github.com/thxtech
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: thxtech
      revision: main
  self:
    path: config
